//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _364700TwitterClone.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public string customerId { get; set; }
        public Nullable<System.DateTime> Orderdate { get; set; }
        public Nullable<System.DateTime> Shippeddate { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public string Shipname { get; set; }
        public string Shipaddres { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
