//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _364700TwitterClone.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public string ProjectId { get; set; }
        public string project_na { get; set; }
        public Nullable<long> Budg { get; set; }
    }
}
