//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _364700TwitterClone.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DEPARTMENT_d1
    {
        public int emp_no { get; set; }
        public string emp_fna { get; set; }
        public string emp_lna { get; set; }
        public string deptID { get; set; }
    }
}
